### ISSUE TITLE
携程价格抓取

### ISSUE THREAD

**Issue by lishuhua940127** [justcodedroid/spider_js#1]

**Comment by lishuhua940127** [comment]
get_eleven(text, url) 这里边的text应该传什么参数？

**Comment by lishuhua940127** [comment]
我这边在线下测试没有问题能抓到正确的价格，但是部署到线上就一直抓取到错误的价格，我怀疑是cookies里边有设置ip导致的，但是我只是单纯改了cookies里边的ip也不行,能留一下你的qq或者你加我qq:898228641

**Comment by lishuhua940127** [comment]
我这边在线下测试没有问题能抓到正确的价格，但是部署到线上就一直抓取到错误的价格，我怀疑是cookies里边有设置ip导致的，但是我只是单纯改了cookies里边的ip也不行,能留一下你的qq或者你加我qq:898228641

**Comment by justcodedroid** [comment]
cookie逆向那边做处理了么？里面有个时间戳需要正则匹配的

**Comment by justcodedroid** [comment]
> 我这边在线下测试没有问题能抓到正确的价格，但是部署到线上就一直抓取到错误的价格，我怀疑是cookies里边有设置ip导致的，但是我只是单纯改了cookies里边的ip也不行,能留一下你的qq或者你加我qq:898228641

cookie逆向那边做处理了么？里面有个时间戳需要正则匹配的。我的微信18235444249

**Comment by justcodedroid** [comment]
> 我这边在线下测试没有问题能抓到正确的价格，但是部署到线上就一直抓取到错误的价格，我怀疑是cookies里边有设置ip导致的，但是我只是单纯改了cookies里边的ip也不行,能留一下你的qq或者你加我qq:898228641

cookie那边我是debug了的。逆向那边只有一个hashcode比较关键，hashcode依赖四个参数。没有发现ip问题

**Comment by justcodedroid** [comment]
cookie的生成基于hotalid，务必按照readme文档运行
